config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    resources :users
    resources :categories
    resources :comments
    resources :posts
    resources :themes

    root to: "users#index"
  end

  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show, :edit, :update] do
    resources :posts, only: [:index]
  end

  resources :themes do
    resources :posts, only: [:new, :create, :show, :edit, :destroy, :update] do
      resources :comments, only: [ :create]
    end
    collection do
      get 'ended'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/theme.rb
class Theme < ApplicationRecord

  belongs_to :user
  belongs_to :category
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :deadline, presence: true
  validates :category_id, presence: true

  mount_uploader :photo, PhotoUploader

end

app/controllers/admin/themes_controller.rb
module Admin
  class ThemesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Theme.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Theme.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :ended, :show]
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  def index
    @themes = policy_scope(Theme).sort_by { |theme| theme.deadline }
    @pending_themes = @themes.select { |theme| !deadline_is_passed?(theme) }
  end

  def ended
    # we show here only themes wich are ended (deadline has been past)
    # allow to dissociate themes which are ended from themes which are pending
    @themes = policy_scope(Theme)
    @ended_themes = @themes.select { |theme| theme if deadline_is_passed?(theme) }
    authorize @themes
  end

  def new
    @theme = Theme.new
    @categories = Category.all.sort_by { |category| category.name}
    authorize @theme
  end

  def create
    @theme = Theme.new(theme_params)
    @categories = Category.all.sort_by { |category| category.name}
    @theme.user = current_user
    authorize @theme
    if @theme.save
      redirect_to theme_path(@theme)
    else
      render :new
    end
  end

  def show
    #calculate the number of day before the end of the inscription period
    @number_of_days = number_of_days_for_apply(@theme.deadline)
    #allow to show all the post of the theme
    @posts = Post.where(theme_id: @theme.id)
    if user_signed_in?
      @post = Post.find_by(theme_id: @theme.id, user_id: current_user.id)
    end
  end

  def edit
    @categories = Category.all.sort_by { |category| category.name}
  end

  def update
    @theme.update(theme_params)
    redirect_to theme_path(@theme), notice: "votre article a été modifé avec succès"
  end

  def destroy
    @theme.destroy
    redirect_to themes_path, notice: "votre article a été supprimé avec succès"
  end


private

  def deadline_is_passed?(theme)
    theme.deadline.past?
  end

  def theme_has_a_post?(theme)
    theme.posts.any?
  end

  def number_of_days_for_apply(deadline)
    #number of day before the theme ends.After this deadline, user can't write a post
    deadline.mjd-DateTime.now.mjd
  end

  def set_theme
    @theme = Theme.find(params[:id])
    authorize @theme
  end

  def theme_params
    params.require(:theme).permit(:name, :deadline, :photo_cache, :category_id, :user_id, :photo)
  end
end

app/views/themes/_theme-contributors.html.erb
<div class="theme__contributors">
  <%= "#{theme.posts.length}" %>
  <%= icon('fas', 'pencil-alt') %>
</div>

app/views/themes/_theme-date.html.erb
<div class="theme__publication">
  <p>Date de publication: <%= theme.deadline.strftime('%d/%m/%Y') %></p>
</div>

app/views/themes/_theme-deadline.html.erb
<div class="theme__publication">
  <p>Date limite: <%= theme.deadline.strftime('%d/%m/%Y') %></p>
</div>
<div class="theme__ongoing">
  <i class="far fa-clock"></i>
  <%= theme.deadline.mjd-DateTime.now.mjd %> j
</div>

app/views/themes/_theme-image.html.erb
<%= cl_image_tag theme.photo, crop: :fill, height: 130, width: 200 %>

app/views/themes/_theme-navbar.html.erb
<div class="theme__navbar">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "En cours", themes_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "Publiés", ended_themes_path, class: "nav-link " %>
    </li>
  </ul>
</div>

<%
=begin%>
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <%= link_to themes_path do %>
    <button class="btn btn-outline-success" type="button">En cours</button>
    <% end %>
    <%= link_to ended_themes_path do %>
    <button class="btn btn-outline-success" type="button">publiés</button>
    <% end %>
  </form>
</nav>
<%
=end%>

app/views/themes/_theme-owner.html.erb
  <div class="theme__owner">
    <p>Thème proposé par</p>
    <% if theme.user.avatar.present? %>
      <% user_avatar = theme.user.avatar  %>
      <%= cl_image_tag user_avatar, crop: :thumb, gravity: :face, width: 30, height: 30, class: "avatar__user__card" %>

  <!-- user hasn't loaded a picture for his avatar yet-->
    <% else %>
      <% user_avatar = "default-avatar.png" %>
      <%= image_tag user_avatar, crop: :thumb, gravity: :face, width: 30, height: 30, class: "avatar__user__card" %>
    <% end %>
    <%= theme.user.pseudo %>
  </div>

app/views/themes/_theme-title.html.erb
<h1 class="theme__card__title"><%= truncate(theme.name, length: 50) %></h1>

app/views/themes/edit.html.erb
<div class="container">
  <h1>Mettez à jour votre article</h1>
  <div>
    <%= simple_form_for (@theme) do |f| %>
      <%= f.input :name, as: :text, label: "Titre de votre thème", placeholder: "décrivez le theme de votre challenge" %>
      <%= f.input :deadline, label: "Deadline de votre thème", order: [:day, :month, :year], placeholder: "précisez la date limite de votre challenge" %>
      <%= f.input :category_id, label: "Sélectionnez votre catégorie", collection: @categories %>
      <p>
        <%= cl_image_tag(@theme.photo, height: 100, Width: "auto") if @theme.photo? %>
        <%= f.file_field :photo %>
        <%= f.hidden_field :photo_cache %>
      </p>
      <p><%= f.button :submit %></p>
    <% end %>
  </div>
</div>

app/views/themes/ended.html.erb
<div class="container ">
  <%= render 'theme-navbar'%>
  <div class="row ">
    <% @ended_themes.each do |theme| %>
      <div class=" col-xs-12 col-sm-6 col-md-4 theme__box">
        <!-- only theme which are still ongoing or past themes which contains at least one post are displayed -->
        <% if theme.photo.present? %>
          <div class=" theme__card">
            <%= render 'shared/theme-card', theme: theme %>
            <%= render 'theme-image', theme: theme %>
            <%= render 'theme-date', theme: theme %>
          </div>
        <% else %>
          <div class=" theme__card">
            <%= render 'shared/theme-card', theme: theme %>
            <%= render 'theme-date', theme: theme %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/themes/index.html.erb
<div class="container ">
  <%= render 'theme-navbar'%>
  <%= render 'shared/pending' %>
</div>

app/views/themes/new.html.erb
<div class="container">
  <h1>Publier un thème</h1>

    <%= simple_form_for (@theme) do |f| %>
    <%= f.error_notification %>

      <p>
        <%= f.input :name, as: :text, label: "Titre de votre thème", placeholder: "décrivez le theme de votre challenge" %>
      </p>

      <p>
        <%= f.input :deadline, label: "Deadline", order: [:day, :month, :year], placeholder: "précisez la date limite de votre challenge" %>
      </p>

      <p>
        <%= f.input :category_id, input_html: {class:'select2'}, placeholder: "séléctionez votre catégorie", label: "Catégorie", collection: @categories %>
      </p>

      <p>
        <%= f.label :photo do %>
          <%= f.file_field :photo %>
          <%= f.hidden_field :photo_cache %>
        <% end %>
      </p>

      <p>
        <%= f.button :submit, "Publier le thème", class: "btn btn-success" %>
      </p>
    <% end %>

</div>

app/views/themes/show.html.erb
<div class="container">
  <div class="row theme__details">
    <div class=" col-xs-12 col-sm-12 col-md-12 ">
      <h1 class="theme__title"><%= "#{@theme.name}" %></h1>
      <div>
        <% if policy(@theme).edit? %>
          <%= link_to(edit_theme_path(@theme), class: "btn btn--secondary") do %>
            <%= icon('fas', 'edit') %>Mettre à jour
          <% end %>
          <%= link_to(theme_path(@theme), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn--secondary") do %>
            <%= icon('fas', 'trash-alt') %>Supprimer
          <% end %>
        <% end %>
        <br><br>
      </div>

      <% if @theme.photo.present? %>
        <%= cl_image_tag @theme.photo, height: 150, width: 200, crop: :fill %>
      <% end %>

      <h2><%= "Thème proposé par:" %></h2>
      <h3>
        <%= link_to user_path(@theme.user) do %>
          <% if @theme.user.avatar.present? %>
            <span>
              <% user_avatar = @theme.user.avatar %>
              <%= cl_image_tag user_avatar, crop: :thumb, gravity: :face, width: 30, height: 30, style: "border-radius: 50%;" %>
            </span>
          <!-- user hasn't loaded a picture for his avatar yet-->
          <% else %>

            <span>
              <% user_avatar = "default-avatar.png" %>
              <%= image_tag user_avatar, crop: :thumb, gravity: :face, width: 30, height: 30 %>
            </span>
          <% end %>
          <%= @theme.user.pseudo  %>
        <% end %>

      </h3>
      <p class="theme__category"><%= @theme.category.name %></p>
      <!-- user can see all the posts for other users if deadline is past, unless a post has been requested as private. In this case, only users who's wrote a post in the theme can see the post -->
      <% if @theme.deadline.past? && policy(@theme).show? %>
        <%= "Theme terminé depuis le #{@theme.deadline.strftime('%d/%m/%Y')}" %><br><br>

        <% @posts.each do |post| %>
          <div>
            <% content = post.content %>
            <% body_content = truncate(content,:length=>60, :omission => "" , :escape => false) %>
            <% if policy(post).show? %>
              <div>
                <div><%= icon('fas', 'unlock-alt') %> Article de <%= post.user.pseudo %></div>
                <div><%= body_content.html_safe + "..."%></div>
                <div><%= link_to "lire l'article", theme_post_path(@theme, post) %></div><br>
              </div>
            <% else %>
              <%= icon('fas', 'lock') %> Article de <%= post.user.pseudo %>

              <div> Ce contenu est privé, seuls les utilisateurs ayant écrit dans le thème sont authorisés à lire l'article</div><br>
            <% end %>
          </div>
        <% end %>
      <% else %>
          <!-- user can update the post if the post exists and theadline is not past -->
        <% if user_signed_in? && Post.exists?(theme_id: @theme.id, user_id: current_user.id) && policy(@post).update?  %>
          <h5 class="post__content"><%= @post.content.html_safe %></h5><br><br>
          <div>
            <%= link_to "Poursuivre votre article", edit_theme_post_path(@theme, @post), class: "btn btn-primary" %>
            <%= link_to "Supprimer mon article", theme_post_path(@theme, @post), method: :delete, data: { confirm: "Etes vous certain de vouloir supprimer votre article? ATTENTION: Cette action est irréversible" }, class: "btn btn-danger" %>
            <h6><%= "Il vous reste #{@number_of_days} jours pour finaliser votre texte" %></h6>
          </div>
        <% else %>
        <!-- if post doesn't exist, user can write a post -->
         <h6><%= "Il vous reste #{@number_of_days} jours pour proposer un texte sur ce theme" %></h6>
         <%= link_to "Ecrire un article", new_theme_post_path(@theme, @post), class: "btn btn-primary" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>