config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    resources :users
    resources :categories
    resources :comments
    resources :posts
    resources :themes

    root to: "users#index"
  end

  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show, :edit, :update] do
    resources :posts, only: [:index]
  end

  resources :themes do
    resources :posts, only: [:new, :create, :show, :edit, :destroy, :update] do
      resources :comments, only: [ :create]
    end
    collection do
      get 'ended'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_avatar_picture.html.erb
<!-- user has loaded a picture for his avatar -->

<% if @user.avatar.present? %>
  <div>
    <% user_avatar = @user.avatar %>
    <%= cl_image_tag user_avatar, crop: :thumb, gravity: :face, width: 100, height: 100, style: "border-radius: 50%;" %>
  </div>
<!-- user hasn't loaded a picture for his avatar yet-->
<% else %>

  <div>
    <% user_avatar = "default-avatar.png" %>
    <%= image_tag user_avatar, crop: :thumb, gravity: :face, width: 100, height: 100 %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <span ><%= image_tag "logo.png", height: 50 %></span>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "+ Publier un thème", new_theme_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Tous les thèmes", themes_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
      <div class="dropdown">
        <!-- user has loaded a picture for his avatar -->
        <% if current_user.avatar.present? %>
          <% user_avatar = current_user.avatar %>
          <%= cl_image_tag user_avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown", crop: :thumb, gravity: :face, width: 100, height: 100 %>
        <!-- user hasn't loaded a picture for his avatar yet-->
        <% else %>
          <% user_avatar = "default-avatar.png" %>
          <%= image_tag user_avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown", crop: :thumb, gravity: :face, width: 100, height: 100 %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Mon profil", user_path(current_user) %></li>
          <li><%= link_to "Mes articles", user_posts_path(current_user) %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "se déconnecter") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "S'identifier"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link", style: "color: blue" %>
      <%= link_to "S'enregistrer", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <% if user_signed_in? %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Mon profil", user_path(current_user) %></li>
          <li><%= link_to "Mes articles", user_posts_path(current_user) %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "se déconnecter") %>
            <% end %>
          </li>
        </ul>
      <% else %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Thèmes en cours", themes_path %></li>
          <li><%= link_to "Se connecter", new_user_session_path %></li>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_pending.html.erb
<div class="row ">
  <% @pending_themes.each do |theme| %>
    <div class=" col-xs-12 col-sm-6 col-md-4 theme__box">
      <!-- only theme which are still ongoing or past themes which contains at least one post are displayed -->
      <% if theme.photo.present? %>
        <div class=" theme__card">
          <%= render 'shared/theme-card', theme: theme %>
          <%= render 'themes/theme-image', theme: theme %>
          <%= render 'themes/theme-deadline', theme: theme %>
        </div>
      <% else %>
        <div class=" theme__card">
          <%= render 'shared/theme-card', theme: theme %>
          <%= render 'themes/theme-deadline', theme: theme %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_post-card.html.erb
<section >
  <%= link_to theme_path(post.theme) do %>
    <p>Thème proposé par</p>
    <% if post.theme.user.avatar.present? %>
      <% user_avatar = post.theme.user.avatar  %>
      <%= cl_image_tag user_avatar, crop: :thumb, gravity: :face, width: 30, height: 30, class: "avatar__user__card" %>
      <%= post.theme.user.pseudo %>
      <h1><strong><%= truncate(post.theme.name, length: 65) %></strong></h1>
  <!-- user hasn't loaded a picture for his avatar yet-->
    <% else %>
      <% user_avatar = "default-avatar.png" %>
      <%= image_tag user_avatar, crop: :thumb, gravity: :face, width: 30, height: 30, class: "avatar__user__card" %>
      <%= post.theme.user.pseudo %>
      <h1><strong><%= truncate(post.theme.name, length: 65) %></strong></h1>
    <% end %>
    <div class="theme__contributors">
      <%= "#{post.theme.posts.length}" %>
      <%= icon('fas', 'pencil-alt') %>
    </div>
  <% end %>
</section>

app/views/shared/_theme-card.html.erb
  <%= link_to theme_path(theme) do %>
    <%= render 'themes/theme-owner', theme: theme %>
    <%= render 'themes/theme-title', theme: theme %>
    <%= render 'themes/theme-contributors', theme: theme %>
  <% end %>